# Version of the docker compose file
version: "3.3"

# Service list
services:
  # Database service
  db:
    # We will using the official mysql version 5.7 images
    image: mysql:5.7
    # We need a volume in our project to store the database
    volumes:
      - ./db_data:/var/lib/mysql
    # The project will always restart when crashing
    restart: always
    # Our environment variable, make sure to fill the .env file with your creditential
    environment:
      # Your root password
      MYSQL_ROOT_PASSWORD: "${MYSQL_ROOT_PASSWORD}"
      # Your database name
      MYSQL_DATABASE: "${MYSQL_DATABASE}"
      # Your database user
      MYSQL_USER: "${MYSQL_USER}"
      # Your user password
      MYSQL_PASSWORD: "${MYSQL_PASSWORD}"
  
  # Php-apache service (version 7.4)
  php_apache:
    depends_on:
      - db
    # We will using the official php-apache version 7.4 images
    image: php:7.4-apache
    # We need a volume in our project to store the php-apache files
    volumes:
      - ./src:/var/www/html/
    ports:
      - "8000:80"
    # The project will always restart when crashing
    restart: always
    environment:
      WORDPRESS_DB_HOST: db:3306
      WORDPRESS_DB_USER: "${MYSQL_USER}"
      WORDPRESS_DB_PASSWORD: "${MYSQL_PASSWORD}"
      WORDPRESS_DB_NAME: "${MYSQL_DATABASE}"

  # Composer service
  composer:
    # working directory 
    working_dir: /src/
    volumes:
      - ./src:/src
    # Official image of composer in version 2
    image: composer:2
    # We will map the 8082 port of container with 80 port on actual machine
    ports:
      - "8081:80"
    command: "composer install"

  # Phpmyadmin service (version 5.1.1)
  phpmyadmin:
  # We will using the official phpmyadmin version 5.1.1 images
    image: phpmyadmin:5.1.1
    environment:
      PMA_HOST: db
      PMA_PORT: 3306
      PMA_ARBITRARY: 1
      MYSQL_ROOT_PASSWORD: "${MYSQL_ROOT_PASSWORD}"
    ports:
      - "8080:80"
    # We will use the same volume as Symfony service
    volumes: 
      - ./phpmyadmin_data:/app

volumes:
  db_data:
  phpmyadmin_data:
  src: